-- =====================================================================
-- Migration 007 — Dispatch & Delivery Management
--
-- Implements: dispatch orders that carry one or more allocated printers
-- to a customer site, with a four-stage lifecycle and proof-of-delivery
-- capture.  On departure each printer is moved to DISPATCHED; on
-- delivery each printer is moved to INSTALLED.  Cancellation from
-- IN_TRANSIT reverts DISPATCHED printers back to ALLOCATED.
--
-- Business rules enforced here / by the API:
--   BR-020  A printer must be in ALLOCATED status to be added to a
--           dispatch order (blocks dispatching unallocated printers).
--   BR-024  A dispatch order must have at least one printer.
--   BR-025  A printer may only appear on one active dispatch order at a
--           time (PENDING / SCHEDULED / IN_TRANSIT).
--
-- Lifecycle:
--   PENDING → SCHEDULED → IN_TRANSIT → DELIVERED  (terminal)
--   PENDING | SCHEDULED | IN_TRANSIT → CANCELLED  (terminal)
-- =====================================================================

-- ---------------------------------------------------------------------
-- Permissions for this module.
-- ---------------------------------------------------------------------
INSERT INTO permissions (code, description) VALUES
  ('dispatch.read',    'View dispatch orders and delivery status'),
  ('dispatch.create',  'Create new dispatch orders'),
  ('dispatch.update',  'Edit dispatch order details and schedule'),
  ('dispatch.deliver', 'Mark orders departed / delivered and capture proof of delivery')
ON DUPLICATE KEY UPDATE description = VALUES(description);

-- ---------------------------------------------------------------------
-- Add DISPATCH_COORDINATOR role (idempotent).
-- ---------------------------------------------------------------------
INSERT INTO roles (code, name, description)
VALUES ('DISPATCH_COORDINATOR', 'Dispatch Coordinator', 'Creates and manages printer dispatch orders and deliveries')
ON DUPLICATE KEY UPDATE name = VALUES(name);

-- ---------------------------------------------------------------------
-- Role → permission grants.
-- ---------------------------------------------------------------------

-- SYSTEM_ADMIN: full access.
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.code = 'SYSTEM_ADMIN'
  AND p.code IN ('dispatch.read', 'dispatch.create', 'dispatch.update', 'dispatch.deliver')
ON DUPLICATE KEY UPDATE role_id = role_id;

-- DISPATCH_COORDINATOR: full dispatch access.
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.code = 'DISPATCH_COORDINATOR'
  AND p.code IN ('dispatch.read', 'dispatch.create', 'dispatch.update', 'dispatch.deliver')
ON DUPLICATE KEY UPDATE role_id = role_id;

-- SALES_MANAGER: read-only visibility.
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.code = 'SALES_MANAGER'
  AND p.code IN ('dispatch.read')
ON DUPLICATE KEY UPDATE role_id = role_id;

-- SALES_REP: read-only visibility.
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.code = 'SALES_REP'
  AND p.code IN ('dispatch.read')
ON DUPLICATE KEY UPDATE role_id = role_id;

-- CEO: read-only visibility.
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.code = 'CEO'
  AND p.code IN ('dispatch.read')
ON DUPLICATE KEY UPDATE role_id = role_id;

-- ---------------------------------------------------------------------
-- Idempotent cleanup — drop in child → parent order so a partial previous
-- run does not leave orphaned tables or mismatched FK types behind.
-- Safe to run on a fresh database (IF EXISTS is a no-op then).
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS dispatch_order_items;
DROP TABLE IF EXISTS dispatch_orders;

-- ---------------------------------------------------------------------
-- dispatch_orders — one header per delivery run.
-- order_no is generated by the API: DSP-YYYY-NNNN.
--
-- FK type audit (must match referenced column exactly):
--   contract_id  BIGINT UNSIGNED  → contracts.id        BIGINT UNSIGNED  ✓
--   site_id      INT UNSIGNED     → customer_sites.id   INT UNSIGNED     ✓
--   created_by   BIGINT UNSIGNED  → users.id            BIGINT UNSIGNED  ✓
-- ---------------------------------------------------------------------
CREATE TABLE dispatch_orders (
  id            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  order_no      VARCHAR(40)     NOT NULL,
  contract_id   BIGINT UNSIGNED NOT NULL,
  site_id       INT UNSIGNED    NULL,
  status        ENUM('PENDING','SCHEDULED','IN_TRANSIT','DELIVERED','CANCELLED')
                NOT NULL DEFAULT 'PENDING',
  planned_date  DATE            NULL,
  courier       VARCHAR(200)    NULL,
  tracking_ref  VARCHAR(100)    NULL,
  departed_at   DATETIME        NULL,
  delivered_at  DATETIME        NULL,
  pod_recipient VARCHAR(200)    NULL,
  pod_notes     TEXT            NULL,
  notes         TEXT            NULL,
  created_by    BIGINT UNSIGNED NOT NULL,
  created_at    DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_dispatch_order_no (order_no),
  CONSTRAINT fk_dsp_contract FOREIGN KEY (contract_id) REFERENCES contracts     (id),
  CONSTRAINT fk_dsp_site     FOREIGN KEY (site_id)     REFERENCES customer_sites (id) ON DELETE SET NULL,
  CONSTRAINT fk_dsp_creator  FOREIGN KEY (created_by)  REFERENCES users          (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- dispatch_order_items — one row per printer on the order.
-- BR-020: printer_id must reference a printer whose status is ALLOCATED
-- at the time the order is created (enforced by the API).
-- BR-025: uniqueness of active dispatch per printer is enforced by API
-- query before insert.
--
-- FK type audit:
--   dispatch_order_id  BIGINT UNSIGNED  → dispatch_orders.id  BIGINT UNSIGNED  ✓
--   printer_id         BIGINT UNSIGNED  → printers.id         BIGINT UNSIGNED  ✓
-- ---------------------------------------------------------------------
CREATE TABLE dispatch_order_items (
  id                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  dispatch_order_id BIGINT UNSIGNED NOT NULL,
  printer_id        BIGINT UNSIGNED NOT NULL,
  notes             TEXT            NULL,
  CONSTRAINT fk_dsp_item_order   FOREIGN KEY (dispatch_order_id) REFERENCES dispatch_orders (id) ON DELETE CASCADE,
  CONSTRAINT fk_dsp_item_printer FOREIGN KEY (printer_id)        REFERENCES printers         (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO schema_migrations (version)
VALUES ('007_dispatch')
ON DUPLICATE KEY UPDATE version = version;
